### ISSUE TITLE
CI-Flake: bud-multiple-platform-no-run fails: error changing to intended-new-root directory 

### ISSUE THREAD

**Issue by cevich** [containers/buildah#3710]
**Description**

With fairly high frequently this test is failing, but sometimes it passes.  This is affecting CI for all PRs for `main` and branch-testing itself.

**Steps to reproduce the issue:**
1. Run CI on a PR or `main` branch
2. `bud-multiple-platform-no-run test` fails ([example from PR 3706](https://cirrus-ci.com/task/4776405517991936?logs=integration_test#L1197))
3. Re-run the task, all tests pass (sometimes)

**Describe the results you received:**

```

[+0853s] # [linux/amd64] [2/2] COMMIT
[+0853s] # Getting image source signatures
...cut...
[+0853s] # [linux/s390x] [2/2] COMMIT
[+0853s] # Getting image source signatures
...cut...
[+0853s] # [linux/ppc64le] [2/2] COMMIT
[+0853s] # Writing manifest to image destination
...cut...
[+0853s] # Writing manifest to image destination
[+0853s] # Storing signatures
[+0853s] # 6df1a5aaabbbb36097fefb40bff149c3623dc9008c8f3708fcc1da7dd564bd58
[+0853s] # --> da98c4525b6
[+0853s] # da98c4525b600114fc89b8ced5fa3c4fb7f681adc65f9cfc31dc7e67640d839c
[+0853s] # error building at STEP "COPY --from=0 /root/Dockerfile.no-run /root/": checking on sources under "/var/tmp/buildah_tests.gbywtb/root/overlay/c0299fe974ccf3e964e1b623e5ee121afc0e63b08dfe9ad37da2b932f75cf0df/merged": error in copier subprocess: error changing to intended-new-root directory "/var/tmp/buildah_tests.gbywtb/root/overlay/c0299fe974ccf3e964e1b623e5ee121afc0e63b08dfe9ad37da2b932f75cf0df/merged": chdir /var/tmp/buildah_tests.gbywtb/root/overlay/c0299fe974ccf3e964e1b623e5ee121afc0e63b08dfe9ad37da2b932f75cf0df/merged: no such file or directory
[+0853s] # [ rc=125 (** EXPECTED 0 **) ]
[+0853s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+0853s] # #| FAIL: exit code is 125; expected 0
[+0853s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+0853s] # /var/tmp/go/src/github.com/containers/buildah/tests
```

**Describe the results you expected:**

`[+0853s] ok 282 bud-multiple-platform-no-run`

**Output of `rpm -q buildah` or `apt list buildah`:**

*Buildah compiled at runtime for PR https://github.com/containers/buildah/pull/3706*

```
conmon-2.0.30-2.fc34-x86_64
containernetworking-plugins-1.0.1-1.fc34-x86_64
containers-common-1-21.fc34-noarch
container-selinux-2.170.0-2.fc34-noarch
crun-1.4-1.fc34-x86_64
libseccomp-2.5.3-1.fc34-x86_64
package cri-o-runc is not installed
package libseccomp2 is not installed
podman-3.4.2-1.fc34-x86_64
runc-1.0.2-2.fc34-x86_64
skopeo-1.5.2-1.fc34-x86_64
slirp4netns-1.1.12-2.fc34-x86_64
```

**Output of `buildah version`:**

```
Version:         1.24.0-dev
Go Version:      go1.16.12
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.0.1
image Version:   5.18.0
Git Commit:      0e6980f
Built:           Wed Jan 12 10:36:14 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

Fedora 35

**Output of `uname -a`:**

Fedora 35

**Output of `cat /etc/containers/storage.conf`:**

Defaults on Fedora 35

**Comment by vrothberg** [comment]
@edsantiago, Mr. Holmes, do you have data points that would suggest when the flake has started?

**Comment by edsantiago** [comment]
My tools for analyzing buildah flakes aren't as polished as those for podman, sorry. This is the best I can do on short notice.
* Integration fedora-33 w/ overlay
  * [[10-20 13:49]](https://api.cirrus-ci.com/v1/task/5710598613762048/logs/integration_test.log)  -- #3593
  * [[11-05 09:05]](https://api.cirrus-ci.com/v1/task/5315038903795712/logs/integration_test.log)  -- #3615
  * [[11-15 13:31]](https://api.cirrus-ci.com/v1/task/5841222460768256/logs/integration_test.log)  -- #3621
* Integration fedora-34 w/ overlay
  * [[10-08 07:24]](https://api.cirrus-ci.com/v1/task/6026192877780992/logs/integration_test.log)  -- #3575
  * [[10-20 13:47]](https://api.cirrus-ci.com/v1/task/4584698706919424/logs/integration_test.log)  -- #3593
  * [[10-21 08:10]](https://api.cirrus-ci.com/v1/task/5701879830151168/logs/integration_test.log)  -- #3593
  * [[10-26 12:41]](https://api.cirrus-ci.com/v1/task/6182424125112320/logs/integration_test.log)  -- #3598
  * [[11-18 13:33]](https://api.cirrus-ci.com/v1/task/4762319931572224/logs/integration_test.log)  -- #3599
  * [[11-29 03:26]](https://api.cirrus-ci.com/v1/task/6701298654380032/logs/integration_test.log)  -- #3651
  * [[12-03 10:40]](https://api.cirrus-ci.com/v1/task/6458405100453888/logs/integration_test.log)  -- #3663
  * [[12-23 07:19]](https://api.cirrus-ci.com/v1/task/4888634892484608/logs/integration_test.log)  -- #3678
  * [[01-10 04:30]](https://api.cirrus-ci.com/v1/task/5545707141595136/logs/integration_test.log)  -- #3695
  * [[01-12 04:21]](https://api.cirrus-ci.com/v1/task/4807717305974784/logs/integration_test.log)  -- #3698
  * [[01-12 06:26]](https://api.cirrus-ci.com/v1/task/6507535002763264/logs/integration_test.log)  -- #3698
  * [[01-12 07:31]](https://api.cirrus-ci.com/v1/task/6628809108619264/logs/integration_test.log)  -- #3698
  * [[01-11 14:25]](https://api.cirrus-ci.com/v1/task/5769176336826368/logs/integration_test.log)  -- #3704
  * [[01-12 10:22]](https://api.cirrus-ci.com/v1/task/4776405517991936/logs/integration_test.log)  -- #3706
* Integration fedora-35 w/ overlay
  * [[11-23 07:13]](https://api.cirrus-ci.com/v1/task/6116626199216128/logs/integration_test.log)  -- #3641
  * [[11-29 19:32]](https://api.cirrus-ci.com/v1/task/4789817687932928/logs/integration_test.log)  -- #3657
  * [[12-15 06:16]](https://api.cirrus-ci.com/v1/task/6116163087237120/logs/integration_test.log)  -- #3674
  * [[12-19 06:02]](https://api.cirrus-ci.com/v1/task/5423938846064640/logs/integration_test.log)  -- #3676
  * [[12-23 07:17]](https://api.cirrus-ci.com/v1/task/6296009776037888/logs/integration_test.log)  -- #3678
  * [[12-20 05:59]](https://api.cirrus-ci.com/v1/task/6243908232413184/logs/integration_test.log)  -- #3681
  * [[01-10 10:13]](https://api.cirrus-ci.com/v1/task/4538251057823744/logs/integration_test.log)  -- #3696
  * [[01-10 12:00]](https://api.cirrus-ci.com/v1/task/6237308847390720/logs/integration_test.log)  -- #3696
  * [[01-12 04:25]](https://api.cirrus-ci.com/v1/task/6215092189528064/logs/integration_test.log)  -- #3698
  * [[01-12 06:28]](https://api.cirrus-ci.com/v1/task/4569983081512960/logs/integration_test.log)  -- #3698
  * [[01-11 14:33]](https://api.cirrus-ci.com/v1/task/6305358040793088/logs/integration_test.log)  -- #3702
  * [[01-12 10:24]](https://api.cirrus-ci.com/v1/task/6605992866611200/logs/integration_test.log)  -- #3706
* Integration ubuntu-2104 w/ overlay
  * [[11-01 14:06]](https://api.cirrus-ci.com/v1/task/6642451797508096/logs/integration_test.log)  -- #3609
  * [[11-01 23:26]](https://api.cirrus-ci.com/v1/task/5677165850132480/logs/integration_test.log)  -- #3609
* Integration ubuntu-2110 w/ overlay
  * [[11-19 11:13]](https://api.cirrus-ci.com/v1/task/4760170904420352/logs/integration_test.log)  -- #3638
  * [[11-29 16:50]](https://api.cirrus-ci.com/v1/task/4714739478560768/logs/integration_test.log)  -- #3656
  * [[12-23 07:23]](https://api.cirrus-ci.com/v1/task/6014534799327232/logs/integration_test.log)  -- #3678
  * [[01-07 14:24]](https://api.cirrus-ci.com/v1/task/6732392848162816/logs/integration_test.log)  -- #3691

**Comment by cevich** [comment]
[Another Ubuntu example from last night's cirrus-cron run.](https://cirrus-ci.com/task/5938293828222976?logs=integration_test#L1198)

**Comment by edsantiago** [comment]
Just now in [Integration fedora-34 w/ overlay](https://api.cirrus-ci.com/v1/task/5436371887194112/logs/integration_test.log) in #3761

**Comment by cevich** [comment]
[Last night on 'main' in cirrus-cron.](https://cirrus-ci.com/task/4712885250162688?logs=integration_test#L1078)

**Comment by edsantiago** [comment]
Seeing a persistent flake in the podman build-under-bud tests, same test, different error message:
```
....
         # Storing signatures
         # 674eef7a6d059cb2477b713f2935a25c6bcc4dc4456352b96fc2b56f93db560d
         # --> dceea6611a9
         # dceea6611a9eee252a60342b9ecbab67c9d4fc65180dd85a1383a9c1acb34ada
         # Error: error creating build container: writing blob: adding layer with blob "sha256:25be9552a8196e51e8dbb75dae1cfe46cad31f01b456c6569017abd31ee1f9b9": ApplyLayer exit status 1 stdout:  stderr: Error after fallback to chroot: no such file or directory
         # [ rc=125 (** EXPECTED 0 **) ]
```

### [bud] 248 bud-multiple-platform-no-run
* fedora-35 : bud podman fedora-35 root host
  * PR #13129
    * [02-04 11:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4634908508291072/html/bud-podman-fedora-35-root-host.log.html#t--00248)
  * PR #12961
    * [01-21 11:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4862497852227584/html/bud-podman-fedora-35-root-host.log.html#t--00248)
  * PR #12913
    * [01-18 18:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6217530388774912/html/bud-podman-fedora-35-root-host.log.html#t--00248)
* fedora-35 : bud remote fedora-35 root host [remote]
  * PR #13129
    * [02-04 11:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5760808415133696/html/bud-remote-fedora-35-root-host.log.html#t--00248)
  * PR #12924
    * [01-19 14:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6479588791418880/html/bud-remote-fedora-35-root-host.log.html#t--00248)

**Comment by cevich** [comment]
This continues to flake fairly regularly in daily branch runs.  [Latest example.](https://cirrus-ci.com/task/4720256957546496?logs=integration_test#L1080)

**Comment by edsantiago** [comment]
*  [unknown image] : Containerized Integration
  * PR #3782
    * [02-15 10:49](https://api.cirrus-ci.com/v1/task/6635871091818496/logs/integration_test.log)
* [unknown image] : Integration fedora-34 w/ overlay
  * PR #3784
    * [02-16 05:14](https://api.cirrus-ci.com/v1/task/5258080974798848/logs/integration_test.log)
  * PR #3761
    * [02-01 08:59](https://api.cirrus-ci.com/v1/task/5436371887194112/logs/integration_test.log)
  * PR #3759
    * [02-01 15:11](https://api.cirrus-ci.com/v1/task/4817239466573824/logs/integration_test.log)
  * PR #3751
    * [01-26 13:37](https://api.cirrus-ci.com/v1/task/5225110498967552/logs/integration_test.log)
* [unknown image] : Integration fedora-35 w/ overlay
  * PR #3752
    * [01-26 18:04](https://api.cirrus-ci.com/v1/task/5430718468718592/logs/integration_test.log)
  * PR #3749
    * [01-26 12:15](https://api.cirrus-ci.com/v1/task/6147828253720576/logs/integration_test.log)
  * PR #3743
    * [01-24 18:33](https://api.cirrus-ci.com/v1/task/6054405265948672/logs/integration_test.log)
* [unknown image] : Integration ubuntu-2110 w/ overlay
  * PR #3766
    * [02-03 09:46](https://api.cirrus-ci.com/v1/task/4929285868748800/logs/integration_test.log)
  * PR #3736
    * [01-24 05:17](https://api.cirrus-ci.com/v1/task/5763523002236928/logs/integration_test.log)
* [unknown image] : Integration ubuntu-2110 w/ vfs
  * PR #3757
    * [02-03 14:22](https://api.cirrus-ci.com/v1/task/5548969823567872/logs/integration_test.log)

**Comment by flouthoc** [comment]
I think there is a race on `c/storage` where layer gets removed by another parallel build. We could remove flakes if we can make `multi-arch` build serially. @nalind Could we make `multi-arch` builds serial until `race` is removed from upstream. I believe one the `SetNames` PR should help but could be different race as well. 

```diff
diff --git a/imagebuildah/build.go b/imagebuildah/build.go
index 77d8b6d5..a71e58aa 100644
--- a/imagebuildah/build.go
+++ b/imagebuildah/build.go
@@ -243,12 +243,12 @@ func BuildDockerfiles(ctx context.Context, store storage.Store, options define.B
                        logPrefix = "[" + platforms.Format(platformSpec) + "] "
                }
                builds.Go(func() error {
+                       instancesLock.Lock()
                        thisID, thisRef, err := buildDockerfilesOnce(ctx, store, logger, logPrefix, platformOptions, paths, files)
                        if err != nil {
                                return err
                        }
                        id, ref = thisID, thisRef
-                       instancesLock.Lock()
                        instances = append(instances, instance{
                                ID:       thisID,
                                Platform: platformSpec,
```

**Comment by nalind** [comment]
I'm pretty sure the race here happens when we need to cancel a build because one stage failed, but others are still running.  The `Executor` `Delete()`s the affected `StageExecutor`, which deletes its `builder`, while its `Execute()` method is still running.

**Comment by flouthoc** [comment]
@nalind I'm not sure about that but for me it happens even when `build` was expected to pass and in uncertain manner. For me some failures were also as `image not known` which is specifically thrown from `c/storage`. 

I also hope that issue is at buildah layer then it would be much easier to get a permanent fix.

**Comment by edsantiago** [comment]
Very funny, github-actions. This is still an enormous annoyance.

**Comment by flouthoc** [comment]
@edsantiago Thanks for reminding, I'll start looking at this again, hopefully with catch race this time.

**Comment by flouthoc** [comment]
Although these races are legit but it should not flake in CI if we are already expecting things to be sequential in CI with `--jobs=0` here https://github.com/containers/buildah/blob/main/tests/bud.bats#L3611 above PR should address that.

**Comment by cevich** [comment]
> we can have a global runtime lock to prevent this.

I don't know the code, but that sounds like it might prevent parallel pulling, no?  IMHO, pulling in parallel is almost universally desirable since bandwidth is vastly cheaper than engineer-time :grinning:

**Comment by flouthoc** [comment]
@cevich We can make it granular so it only locks for pull with same name, so it should still allow other pulls in parallel. Anyways problem could be entirely different. 

@edsantiago @cevich I have a small question, do we have this flake since inception of `bud-multiple-platform-no-run` or was this flake introduced somewhere in the middle. Following question would help me diagnose if any commit in `c/storage`, `c/image` or `buildah` introduced these race conditions later.

**Comment by edsantiago** [comment]
The first instance I see was 2021-10-08 but unfortunately those logs are gone.

**Comment by cevich** [comment]
This has been a problem for a very long time.  I seem to remember Miloslav or Nalin mentioning the underlying name/pull race problem being in c/storage or c/image.  At the time we just ignored it assuming it would be rare :grinning: It's worth talking to them about it, I think they know right where the issue is.

**Comment by nalind** [comment]
> @nalind I think we have three different races happening here:
> 
>     * **(Happens in both rootless and rootful):** I believe race happens on `pull` API cause I think `c/storage` does not maps `arch` and `name` together so pull from one arch overrides another pull causing `error creating build container: error locating pulled image "registry.access.redhat.com/ubi8-micro:latest" name in containers storage: registry.access.redhat.com/ubi8-micro:latest: image not known `

We fixed this exact problem in https://github.com/containers/common/pull/688, but the helper function it introduced is no longer being used, so it's possible we broke it since then.

**Comment by cevich** [comment]
I'm not surprised, from what I remember from discussions before, there was some unholy (re-implementation level) hell :imp: somewhere in c/storage or image that nobody wanted to touch.  So we collectively stuck out heads in the sand.  I wouldn't doubt for a second, that's what's biting us now :confused: I bet @mtrmac remembers.

**Comment by mtrmac** [comment]
The two hairy issues I have identified earlier are https://github.com/containers/storage/issues/1147 (with two proposed fixes) and https://github.com/containers/storage/issues/1136 (with no fix at all).

Those might be related, but I don’t know enough to be able to identify them from logs as definite causes. Note that both should _only_ happen on some kind of failure or forced abort (e.g. a timeout + SIGKILL), not just races during ordinary operation.

During ordinary operation, `layerStore` is supposed to always be locked before looking up a layer by ID, continuing for the duration of any use use of that layer — so it should, AFAIK never be possible for any external c/storage user to be able to refer to deleted or inconsistent overlayfs content: either the layer exists by the time the lock is obtained, and it should be complete and consistent, or it doesn’t exist, and the code should fail with “layer not found”.

(“Layer not found” races would not surprise me at all, for code paths that leave the c/storage lock scope but assume the storage is substantially unchanged — e.g. an ordinary pull might find a base layer but then fail to apply a child layer if the base layer has been removed in the meantime. But again, that’s not what these logs show.)

So either it’s one of these unclean abort / inconsistency situations, or perhaps there might be a code path that should be locking the layerStore but isn’t doing so. I did check for those situations some time ago, and I couldn’t find anything at least on the major code paths involved in pulls/deletes, but I could well have missed something, e.g. because I was looking at the pull/run paths, not at anything involved in builds.

**Comment by cevich** [comment]
This issue is still flaking frequently.  [Recent Example in podman CI.](https://cirrus-ci.com/task/5671513033539584)

**Comment by cevich** [comment]
[Happened in buildah-main yesterday.](https://cirrus-ci.com/task/6175676628729856?logs=integration_test#L1000)

**Comment by edsantiago** [comment]
Dum de dum, [still happening](https://api.cirrus-ci.com/v1/artifact/task/6433148018884608/html/bud-podman-fedora-36-root-host.log.html#t--00294)

**Comment by cevich** [comment]
Oddly, I haven't seen this pop up recently, @edsantiago and @lsm5, do you remember anything in podman-monitor for August?

**Comment by edsantiago** [comment]
On podman, last seen [Aug 2](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6429908455915520/html/bud-remote-fedora-35-root-host.log.html#t--00250)

**Comment by cevich** [comment]
Interesting, I remember this issue reproducing a lot more frequently.  We saw it all the time (several times per week) in Buildah and Podman CI.  Still, I s'pose maybe timings could have changed causing it to flake less :disappointed: .  In any case, I also don't recall any recent activity on a fix either.  @flouthoc where are we at with this, do you recall if anything else was done?

**Comment by flouthoc** [comment]
@cevich I don't think this is fixed at all, we don't see it occurring as frequently now because we tweaked concurrency in tests for multi-platform builds so it's just suppressed. Last time when i was working on this i was unable to catch the race maybe i'll give it a shot again.

**Comment by cevich** [comment]
> maybe i'll give it a shot again.

Seems even more difficult now, at least in "wild-CI".  Though generally I agree that some kind of reproducer would be helpful here.  Do you have a notion of where the problem comes from and perhaps can that code be instrumented to force it to occur more reliably/frequently?

**Comment by cevich** [comment]
e.g. if you want to spawn a VM with more CPUs from `hack/get_ci_vm.sh`, you can edit the script locally and change the `GCLOUD_CPUS` value as needed.

**Comment by cevich** [comment]
IMHO we can close this.  I haven't seen any occurrences happen in the daily jobs for quite a while.

**Comment by edsantiago** [comment]
I wonder if this might have something to do with why we're not seeing the flake any more? https://github.com/containers/buildah/blob/4f8706bb3e15a18a64567e7fc3feb9a37bc2e1a4/tests/bud.bats#L5285-L5288

**Comment by cevich** [comment]
Damn, I bet that's exactly the reason :disappointed: I would be in favor of removing that or possibly making it conditional on an env-var or something.
