### ISSUE TITLE
buildah bud : on commit error copying layers and metadata

### ISSUE THREAD

**Issue by olivierGATSNCF** [containers/buildah#974]
**Description**

I'm trying to build a buildah image  that has an image from openshift / base-centos7

With docker I can build my image buildah.
With buildah bud, during the commit of the image an error occurs which seems to be due to a bad reading of the history of the manifest of the image from openshift/base-centos7:
```
error copying layers and metadata: Error initializing source containers-storage:base-centos7-working-container: internal error: history lists 5 non-empty layers, but we have 16 layers on disk.
```

buildah version 1.1 or 1.3 the result is the same.

**Steps to reproduce the issue:**
1. buildah bud --format docker --build-arg HTTP_PROXY=http://xxxx --build-arg HTTPS_PROXY=http://xxxx --build-arg http_proxy=http://xxxx --build-arg https_proxy=http://xxxx --tls-verify=false --pull -f Dockerfile --tag registyr/buildtools/buildah_v1:2 --label buildtools.build-date=20180828 --label buildtools.git-commit=f2a6485b785d5e07d92bb1bc55be75279fb620a2 --build-arg no_proxy=registry --build-arg IMAGE_VERSION=2 .

**Describe the results you received:**
STEP 11: CMD ["/bin/bash"]    
STEP 12: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker-eul-releases-nexusm-repo-gpf.apps.eul.sncf.fr/buildtools/buildah_v1:2
EXITCODE   0error copying layers and metadata: Error initializing source containers-storage:base-centos7-working-container: internal error: history lists 5 non-empty layers, but we have 16 layers on disk

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**
(buildah used to build the image is  a docker container. )
```
package buildah is not installed
```

**Output of `buildah version`:**

```
buildah version
Version:         1.3
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      4888163
Built:           Thu Aug 23 14:48:55 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 
```

**Output of `uname -a`:**

```
Linux jenkins-slave-52fwh-mhkn5 3.10.0-862.9.1.el7.x86_64 #1 SMP Wed Jun 27 04:30:39 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# mountopt specifies extra mount options used when mounting the thin devices.
# mountopt = ""

# use_deferred_removal Marking device for deferred removal
# use_deferred_removal = "True"

# use_deferred_deletion Marking device for deferred deletion
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by olivierGATSNCF** [comment]
buildah inspect of openshift/base-centos7:latest
{
    "Type": "buildah 0.0.1",
    "FromImage": "openshift/base-centos7:latest",
    "FromImageID": "4842f0bd3d610c5cdb1c74e6c7f664b4789b6453e54bc507faf4a47823cc2ba0",
    "Config": "",
    "Manifest": "{\n   \"schemaVersion\": 1,\n   \"name\": \"openshift/base-centos7\",\n   \"tag\": \"latest\",\n   \"architecture\": \"amd64\",\n   \"fsLayers\": [\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:8a3400b7e31a55323583e3d585b3b0be56d9f7ae563187aec96d47ef5419982a\"\n      },\n      {\n         \"blobSum\": \"sha256:78efc9e155c4f5ac3665c4ef14339c305672468520dc0d5ad5a254ce90a1ec28\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:734fb161cf896cf5c25a9a857a4b4d267bb5a59d5acf9ba846278ab3f3d1f5d5\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      },\n      {\n         \"blobSum\": \"sha256:45a2e645736c4c66ef34acce2407ded21f7a9b231199d3b92d6c9776df264729\"\n      },\n      {\n         \"blobSum\": \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\"\n      }\n   ],\n   \"history\": [\n      {\n         \"v1Compatibility\": \"{\\\"architecture\\\":\\\"amd64\\\",\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"config\\\":{\\\"Hostname\\\":\\\"1b0d6163fdc2\\\",\\\"Domainname\\\":\\\"\\\",\\\"User\\\":\\\"\\\",\\\"AttachStdin\\\":false,\\\"AttachStdout\\\":false,\\\"AttachStderr\\\":false,\\\"Tty\\\":false,\\\"OpenStdin\\\":false,\\\"StdinOnce\\\":false,\\\"Env\\\":[\\\"PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\",\\\"STI_SCRIPTS_URL=image:///usr/libexec/s2i\\\",\\\"STI_SCRIPTS_PATH=/usr/libexec/s2i\\\",\\\"HOME=/opt/app-root/src\\\",\\\"BASH_ENV=/opt/app-root/etc/scl_enable\\\",\\\"ENV=/opt/app-root/etc/scl_enable\\\",\\\"PROMPT_COMMAND=. /opt/app-root/etc/scl_enable\\\"],\\\"Cmd\\\":[\\\"base-usage\\\"],\\\"ArgsEscaped\\\":true,\\\"Image\\\":\\\"sha256:28ae656c7bcdcb521b2328f725cbea1ec15b5959f1e9d1c8495d4b013a15af02\\\",\\\"Volumes\\\":null,\\\"WorkingDir\\\":\\\"/opt/app-root/src\\\",\\\"Entrypoint\\\":[\\\"container-entrypoint\\\"],\\\"OnBuild\\\":[],\\\"Labels\\\":{\\\"build-date\\\":\\\"20161214\\\",\\\"io.openshift.builder-base-version\\\":\\\"bfd4736\\\",\\\"io.openshift.s2i.scripts-url\\\":\\\"image:///usr/libexec/s2i\\\",\\\"io.s2i.scripts-url\\\":\\\"image:///usr/libexec/s2i\\\",\\\"license\\\":\\\"GPLv2\\\",\\\"name\\\":\\\"CentOS Base Image\\\",\\\"vendor\\\":\\\"CentOS\\\"}},\\\"container\\\":\\\"211fbe72ff045a276f2e57d3762b923f747b41bb16d82d55987bf9e0140cff5b\\\",\\\"container_config\\\":{\\\"Hostname\\\":\\\"1b0d6163fdc2\\\",\\\"Domainname\\\":\\\"\\\",\\\"User\\\":\\\"\\\",\\\"AttachStdin\\\":false,\\\"AttachStdout\\\":false,\\\"AttachStderr\\\":false,\\\"Tty\\\":false,\\\"OpenStdin\\\":false,\\\"StdinOnce\\\":false,\\\"Env\\\":[\\\"PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\",\\\"STI_SCRIPTS_URL=image:///usr/libexec/s2i\\\",\\\"STI_SCRIPTS_PATH=/usr/libexec/s2i\\\",\\\"HOME=/opt/app-root/src\\\",\\\"BASH_ENV=/opt/app-root/etc/scl_enable\\\",\\\"ENV=/opt/app-root/etc/scl_enable\\\",\\\"PROMPT_COMMAND=. /opt/app-root/etc/scl_enable\\\"],\\\"Cmd\\\":[\\\"/bin/sh\\\",\\\"-c\\\",\\\"#(nop) \\\",\\\"LABEL io.openshift.builder-base-version=bfd4736\\\"],\\\"ArgsEscaped\\\":true,\\\"Image\\\":\\\"sha256:28ae656c7bcdcb521b2328f725cbea1ec15b5959f1e9d1c8495d4b013a15af02\\\",\\\"Volumes\\\":null,\\\"WorkingDir\\\":\\\"/opt/app-root/src\\\",\\\"Entrypoint\\\":[\\\"container-entrypoint\\\"],\\\"OnBuild\\\":[],\\\"Labels\\\":{\\\"build-date\\\":\\\"20161214\\\",\\\"io.openshift.builder-base-version\\\":\\\"bfd4736\\\",\\\"io.openshift.s2i.scripts-url\\\":\\\"image:///usr/libexec/s2i\\\",\\\"io.s2i.scripts-url\\\":\\\"image:///usr/libexec/s2i\\\",\\\"license\\\":\\\"GPLv2\\\",\\\"name\\\":\\\"CentOS Base Image\\\",\\\"vendor\\\":\\\"CentOS\\\"}},\\\"created\\\":\\\"2017-02-01T12:38:50.598676504Z\\\",\\\"docker_version\\\":\\\"1.12.2-rc2\\\",\\\"id\\\":\\\"bb81a093d169548a95e5f050a5a74322313bcb4884252b234a1a41bc7d502055\\\",\\\"os\\\":\\\"linux\\\",\\\"parent\\\":\\\"3a300bfbb590e597674d5dea9b4bcd87818ac91d81c1917c8f7f8d955a738c48\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"3a300bfbb590e597674d5dea9b4bcd87818ac91d81c1917c8f7f8d955a738c48\\\",\\\"parent\\\":\\\"99c6eb8b1b328ef4a9602bac9b5bdecda1fea5cf79bc5069e4be1d179241424c\\\",\\\"created\\\":\\\"2017-02-01T12:38:48.448663571Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  CMD [\\\\\\\"base-usage\\\\\\\"]\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"99c6eb8b1b328ef4a9602bac9b5bdecda1fea5cf79bc5069e4be1d179241424c\\\",\\\"parent\\\":\\\"24faf900b585571c6d7d569ae6bdcdd5503280878cbae5860b3c1a4f583ad7b6\\\",\\\"created\\\":\\\"2017-02-01T12:38:46.27564274Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  ENTRYPOINT [\\\\\\\"container-entrypoint\\\\\\\"]\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"24faf900b585571c6d7d569ae6bdcdd5503280878cbae5860b3c1a4f583ad7b6\\\",\\\"parent\\\":\\\"a4f444b1ed32590cb3f1e104a7a40e246d421d2be39fbc4bdf2d29d1d999c6aa\\\",\\\"created\\\":\\\"2017-02-01T12:38:44.153641548Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  WORKDIR /opt/app-root/src\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"a4f444b1ed32590cb3f1e104a7a40e246d421d2be39fbc4bdf2d29d1d999c6aa\\\",\\\"parent\\\":\\\"cf7dbbd69361f2af452bd600cd5845278d43477c66e9a1cb41897d45df17f83a\\\",\\\"created\\\":\\\"2017-02-01T12:38:41.964912469Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop) COPY dir:db143564578605b4cc3f4c2825bf5ea1812354bddf5784d97bd1c3caacfdbc03 in /usr/bin/ \\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\"}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"cf7dbbd69361f2af452bd600cd5845278d43477c66e9a1cb41897d45df17f83a\\\",\\\"parent\\\":\\\"f93b41062a07ceedb1c90b6b3be4c4fd605dd6b6f7792cad0b9d9bb4083d5ac4\\\",\\\"created\\\":\\\"2017-02-01T12:38:38.610543803Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 \\\\u0026\\\\u0026   INSTALL_PKGS=\\\\\\\"autoconf   automake   bsdtar   bzip2   findutils   gcc-c++   gd-devel   gdb   gettext   git   libcurl-devel   libxml2-devel   libxslt-devel   lsof   make   mariadb-devel   mariadb-libs   openssl-devel   patch   postgresql-devel   procps-ng   scl-utils   sqlite-devel   tar   unzip   wget   which   yum-utils   zlib-devel\\\\\\\" \\\\u0026\\\\u0026   mkdir -p ${HOME}/.pki/nssdb \\\\u0026\\\\u0026   chown -R 1001:0 ${HOME}/.pki \\\\u0026\\\\u0026   yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS \\\\u0026\\\\u0026   rpm -V $INSTALL_PKGS \\\\u0026\\\\u0026   yum clean all -y \\\\u0026\\\\u0026   useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin       -c \\\\\\\"Default Application User\\\\\\\" default \\\\u0026\\\\u0026   chown -R 1001:0 /opt/app-root\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\"}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"f93b41062a07ceedb1c90b6b3be4c4fd605dd6b6f7792cad0b9d9bb4083d5ac4\\\",\\\"parent\\\":\\\"8944e68374c4135149e553498387db08ff3ff945df10747f605f298f47c2bcb8\\\",\\\"created\\\":\\\"2017-02-01T12:35:18.34175466Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  ENV BASH_ENV=/opt/app-root/etc/scl_enable ENV=/opt/app-root/etc/scl_enable PROMPT_COMMAND=. /opt/app-root/etc/scl_enable\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"8944e68374c4135149e553498387db08ff3ff945df10747f605f298f47c2bcb8\\\",\\\"parent\\\":\\\"b7a9f751f2d64842b35f56eebd2f87929aa4e34d440cd551b394344972b418ba\\\",\\\"created\\\":\\\"2017-02-01T12:35:16.320837707Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop) COPY file:92abfe3dd1d63ab45469e0920939e615b734160a4ddb9a9b745f18093fe54a92 in /opt/app-root/etc/scl_enable \\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\"}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"b7a9f751f2d64842b35f56eebd2f87929aa4e34d440cd551b394344972b418ba\\\",\\\"parent\\\":\\\"e78b2fb0ee8d9af79e3dae18cc9702c087ca9de69ae071dbb74a27becf4bf07a\\\",\\\"created\\\":\\\"2017-02-01T12:35:14.532740148Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  ENV STI_SCRIPTS_URL=image:///usr/libexec/s2i STI_SCRIPTS_PATH=/usr/libexec/s2i HOME=/opt/app-root/src PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"e78b2fb0ee8d9af79e3dae18cc9702c087ca9de69ae071dbb74a27becf4bf07a\\\",\\\"parent\\\":\\\"4ef929f1a369bd03c4c91e32b0e6d62c0fbdae92a7563aeb657b3102ade0f62a\\\",\\\"created\\\":\\\"2017-02-01T12:35:12.609704883Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  LABEL io.openshift.s2i.scripts-url=image:///usr/libexec/s2i io.s2i.scripts-url=image:///usr/libexec/s2i\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"4ef929f1a369bd03c4c91e32b0e6d62c0fbdae92a7563aeb657b3102ade0f62a\\\",\\\"parent\\\":\\\"08e1d80f2b80b86e13801c44c691fbc5812755972d44c1b2942f7f0cfa00a438\\\",\\\"created\\\":\\\"2017-02-01T12:35:10.223863578Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  MAINTAINER Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\"]},\\\"author\\\":\\\"Jakub Hadvig \\\\u003cjhadvig@redhat.com\\\\u003e\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"08e1d80f2b80b86e13801c44c691fbc5812755972d44c1b2942f7f0cfa00a438\\\",\\\"parent\\\":\\\"a04895de19968b0665115154295009f75bcba85eb71dbb7fe6ae14cb8c95a475\\\",\\\"created\\\":\\\"2016-12-15T18:21:23.875991987Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  CMD [\\\\\\\"/bin/bash\\\\\\\"]\\\"]},\\\"author\\\":\\\"https://github.com/CentOS/sig-cloud-instance-images\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"a04895de19968b0665115154295009f75bcba85eb71dbb7fe6ae14cb8c95a475\\\",\\\"parent\\\":\\\"0a444b299d5a7868b640b12020a2684a72167b6710037b6bd4933f6713b2b47c\\\",\\\"created\\\":\\\"2016-12-15T18:21:23.00781987Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  LABEL name=CentOS Base Image vendor=CentOS license=GPLv2 build-date=20161214\\\"]},\\\"author\\\":\\\"https://github.com/CentOS/sig-cloud-instance-images\\\",\\\"throwaway\\\":true}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"0a444b299d5a7868b640b12020a2684a72167b6710037b6bd4933f6713b2b47c\\\",\\\"parent\\\":\\\"3690474eb5b4b26fdfbd89c6e159e8cc376ca76ef48032a30fa6aafd56337880\\\",\\\"created\\\":\\\"2016-12-15T18:21:21.197722058Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop) ADD file:940c77b6724c00d4208cc72169a63951eaa605672bcc5902ab2013cbae107434 in / \\\"]},\\\"author\\\":\\\"https://github.com/CentOS/sig-cloud-instance-images\\\"}\"\n      },\n      {\n         \"v1Compatibility\": \"{\\\"id\\\":\\\"3690474eb5b4b26fdfbd89c6e159e8cc376ca76ef48032a30fa6aafd56337880\\\",\\\"created\\\":\\\"2016-08-30T18:18:45.109943798Z\\\",\\\"container_config\\\":{\\\"Cmd\\\":[\\\"/bin/sh -c #(nop)  MAINTAINER https://github.com/CentOS/sig-cloud-instance-images\\\"]},\\\"author\\\":\\\"https://github.com/CentOS/sig-cloud-instance-images\\\",\\\"throwaway\\\":true}\"\n      }\n   ],\n   \"signatures\": [\n      {\n         \"header\": {\n            \"jwk\": {\n               \"crv\": \"P-256\",\n               \"kid\": \"4JZX:4GKH:4CAC:43I5:LN5N:LR3S:RNKB:A7C3:FUT6:S65E:BMHW:2C5D\",\n               \"kty\": \"EC\",\n               \"x\": \"pXN_6udDwh3mCUYpyBHvTRnD4tvjLezZcgA7_XQqiWM\",\n               \"y\": \"re2MGRxg5DG-aLMe-mvvKt9znlKLAU9zTMmSNxsd8Qk\"\n            },\n            \"alg\": \"ES256\"\n         },\n         \"signature\": \"0UwjKFeQ1TwoG51Nck4LzANhYlrn1P_A5Clx4h8RHQ8UEFRyHWC7KpNVBvyd_pbXcjDspoMA57K_s060wFyGGw\",\n         \"protected\": \"eyJmb3JtYXRMZW5ndGgiOjExNjc4LCJmb3JtYXRUYWlsIjoiQ24wIiwidGltZSI6IjIwMTgtMDgtMjJUMTM6NTU6MTFaIn0\"\n      }\n   ]\n}",
    "Container": "",
    "ContainerID": "",
    "MountPoint": "",
    "ProcessLabel": "",
    "MountLabel": "",
    "ImageAnnotations": {},
    "ImageCreatedBy": "",
    "OCIv1": {
        "created": "2017-02-01T12:38:50.598676504Z",
        "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
        "architecture": "amd64",
        "os": "linux",
        "config": {
            "Env": [
                "PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STI_SCRIPTS_URL=image:///usr/libexec/s2i",
                "STI_SCRIPTS_PATH=/usr/libexec/s2i",
                "HOME=/opt/app-root/src",
                "BASH_ENV=/opt/app-root/etc/scl_enable",
                "ENV=/opt/app-root/etc/scl_enable",
                "PROMPT_COMMAND=. /opt/app-root/etc/scl_enable"
            ],
            "Entrypoint": [
                "container-entrypoint"
            ],
            "Cmd": [
                "base-usage"
            ],
            "WorkingDir": "/opt/app-root/src",
            "Labels": {
                "build-date": "20161214",
                "io.openshift.builder-base-version": "bfd4736",
                "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
                "io.s2i.scripts-url": "image:///usr/libexec/s2i",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "rootfs": {
            "type": "layers",
            "diff_ids": [
                "",
                "",
                "",
                ""
            ]
        },
        "history": [
            {
                "created": "2016-08-30T18:18:45.109943798Z",
                "created_by": "/bin/sh -c #(nop)  MAINTAINER https://github.com/CentOS/sig-cloud-instance-images",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "empty_layer": true
            },
            {
                "created": "2016-12-15T18:21:21.197722058Z",
                "created_by": "/bin/sh -c #(nop) ADD file:940c77b6724c00d4208cc72169a63951eaa605672bcc5902ab2013cbae107434 in / ",
                "author": "https://github.com/CentOS/sig-cloud-instance-images"
            },
            {
                "created": "2016-12-15T18:21:23.00781987Z",
                "created_by": "/bin/sh -c #(nop)  LABEL name=CentOS Base Image vendor=CentOS license=GPLv2 build-date=20161214",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "empty_layer": true
            },
            {
                "created": "2016-12-15T18:21:23.875991987Z",
                "created_by": "/bin/sh -c #(nop)  CMD [\"/bin/bash\"]",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:10.223863578Z",
                "created_by": "/bin/sh -c #(nop)  MAINTAINER Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:12.609704883Z",
                "created_by": "/bin/sh -c #(nop)  LABEL io.openshift.s2i.scripts-url=image:///usr/libexec/s2i io.s2i.scripts-url=image:///usr/libexec/s2i",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:14.532740148Z",
                "created_by": "/bin/sh -c #(nop)  ENV STI_SCRIPTS_URL=image:///usr/libexec/s2i STI_SCRIPTS_PATH=/usr/libexec/s2i HOME=/opt/app-root/src PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:16.320837707Z",
                "created_by": "/bin/sh -c #(nop) COPY file:92abfe3dd1d63ab45469e0920939e615b734160a4ddb9a9b745f18093fe54a92 in /opt/app-root/etc/scl_enable ",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e"
            },
            {
                "created": "2017-02-01T12:35:18.34175466Z",
                "created_by": "/bin/sh -c #(nop)  ENV BASH_ENV=/opt/app-root/etc/scl_enable ENV=/opt/app-root/etc/scl_enable PROMPT_COMMAND=. /opt/app-root/etc/scl_enable",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:38.610543803Z",
                "created_by": "/bin/sh -c rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 \u0026\u0026   INSTALL_PKGS=\"autoconf   automake   bsdtar   bzip2   findutils   gcc-c++   gd-devel   gdb   gettext   git   libcurl-devel   libxml2-devel   libxslt-devel   lsof   make   mariadb-devel   mariadb-libs   openssl-devel   patch   postgresql-devel   procps-ng   scl-utils   sqlite-devel   tar   unzip   wget   which   yum-utils   zlib-devel\" \u0026\u0026   mkdir -p ${HOME}/.pki/nssdb \u0026\u0026   chown -R 1001:0 ${HOME}/.pki \u0026\u0026   yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS \u0026\u0026   rpm -V $INSTALL_PKGS \u0026\u0026   yum clean all -y \u0026\u0026   useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin       -c \"Default Application User\" default \u0026\u0026   chown -R 1001:0 /opt/app-root",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e"
            },
            {
                "created": "2017-02-01T12:38:41.964912469Z",
                "created_by": "/bin/sh -c #(nop) COPY dir:db143564578605b4cc3f4c2825bf5ea1812354bddf5784d97bd1c3caacfdbc03 in /usr/bin/ ",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e"
            },
            {
                "created": "2017-02-01T12:38:44.153641548Z",
                "created_by": "/bin/sh -c #(nop)  WORKDIR /opt/app-root/src",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:46.27564274Z",
                "created_by": "/bin/sh -c #(nop)  ENTRYPOINT [\"container-entrypoint\"]",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:48.448663571Z",
                "created_by": "/bin/sh -c #(nop)  CMD [\"base-usage\"]",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:50.598676504Z",
                "created_by": "/bin/sh -c #(nop)  LABEL io.openshift.builder-base-version=bfd4736",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            }
        ]
    },
    "Docker": {
        "created": "2017-02-01T12:38:50.598676504Z",
        "container": "211fbe72ff045a276f2e57d3762b923f747b41bb16d82d55987bf9e0140cff5b",
        "container_config": {
            "Hostname": "1b0d6163fdc2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STI_SCRIPTS_URL=image:///usr/libexec/s2i",
                "STI_SCRIPTS_PATH=/usr/libexec/s2i",
                "HOME=/opt/app-root/src",
                "BASH_ENV=/opt/app-root/etc/scl_enable",
                "ENV=/opt/app-root/etc/scl_enable",
                "PROMPT_COMMAND=. /opt/app-root/etc/scl_enable"
            ],
            "Cmd": [
                "base-usage"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:28ae656c7bcdcb521b2328f725cbea1ec15b5959f1e9d1c8495d4b013a15af02",
            "Volumes": null,
            "WorkingDir": "/opt/app-root/src",
            "Entrypoint": [
                "container-entrypoint"
            ],
            "OnBuild": [],
            "Labels": {
                "build-date": "20161214",
                "io.openshift.builder-base-version": "bfd4736",
                "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
                "io.s2i.scripts-url": "image:///usr/libexec/s2i",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
        "config": {
            "Hostname": "1b0d6163fdc2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STI_SCRIPTS_URL=image:///usr/libexec/s2i",
                "STI_SCRIPTS_PATH=/usr/libexec/s2i",
                "HOME=/opt/app-root/src",
                "BASH_ENV=/opt/app-root/etc/scl_enable",
                "ENV=/opt/app-root/etc/scl_enable",
                "PROMPT_COMMAND=. /opt/app-root/etc/scl_enable"
            ],
            "Cmd": [
                "base-usage"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:28ae656c7bcdcb521b2328f725cbea1ec15b5959f1e9d1c8495d4b013a15af02",
            "Volumes": null,
            "WorkingDir": "/opt/app-root/src",
            "Entrypoint": [
                "container-entrypoint"
            ],
            "OnBuild": [],
            "Labels": {
                "build-date": "20161214",
                "io.openshift.builder-base-version": "bfd4736",
                "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
                "io.s2i.scripts-url": "image:///usr/libexec/s2i",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "architecture": "amd64",
        "os": "linux",
        "rootfs": {
            "type": "layers",
            "diff_ids": [
                "",
                "",
                "",
                ""
            ]
        },
        "history": [
            {
                "created": "2016-08-30T18:18:45.109943798Z",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "created_by": "/bin/sh -c #(nop)  MAINTAINER https://github.com/CentOS/sig-cloud-instance-images",
                "empty_layer": true
            },
            {
                "created": "2016-12-15T18:21:21.197722058Z",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "created_by": "/bin/sh -c #(nop) ADD file:940c77b6724c00d4208cc72169a63951eaa605672bcc5902ab2013cbae107434 in / "
            },
            {
                "created": "2016-12-15T18:21:23.00781987Z",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "created_by": "/bin/sh -c #(nop)  LABEL name=CentOS Base Image vendor=CentOS license=GPLv2 build-date=20161214",
                "empty_layer": true
            },
            {
                "created": "2016-12-15T18:21:23.875991987Z",
                "author": "https://github.com/CentOS/sig-cloud-instance-images",
                "created_by": "/bin/sh -c #(nop)  CMD [\"/bin/bash\"]",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:10.223863578Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  MAINTAINER Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:12.609704883Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  LABEL io.openshift.s2i.scripts-url=image:///usr/libexec/s2i io.s2i.scripts-url=image:///usr/libexec/s2i",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:14.532740148Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  ENV STI_SCRIPTS_URL=image:///usr/libexec/s2i STI_SCRIPTS_PATH=/usr/libexec/s2i HOME=/opt/app-root/src PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:35:16.320837707Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop) COPY file:92abfe3dd1d63ab45469e0920939e615b734160a4ddb9a9b745f18093fe54a92 in /opt/app-root/etc/scl_enable "
            },
            {
                "created": "2017-02-01T12:35:18.34175466Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  ENV BASH_ENV=/opt/app-root/etc/scl_enable ENV=/opt/app-root/etc/scl_enable PROMPT_COMMAND=. /opt/app-root/etc/scl_enable",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:38.610543803Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 \u0026\u0026   INSTALL_PKGS=\"autoconf   automake   bsdtar   bzip2   findutils   gcc-c++   gd-devel   gdb   gettext   git   libcurl-devel   libxml2-devel   libxslt-devel   lsof   make   mariadb-devel   mariadb-libs   openssl-devel   patch   postgresql-devel   procps-ng   scl-utils   sqlite-devel   tar   unzip   wget   which   yum-utils   zlib-devel\" \u0026\u0026   mkdir -p ${HOME}/.pki/nssdb \u0026\u0026   chown -R 1001:0 ${HOME}/.pki \u0026\u0026   yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS \u0026\u0026   rpm -V $INSTALL_PKGS \u0026\u0026   yum clean all -y \u0026\u0026   useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin       -c \"Default Application User\" default \u0026\u0026   chown -R 1001:0 /opt/app-root"
            },
            {
                "created": "2017-02-01T12:38:41.964912469Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop) COPY dir:db143564578605b4cc3f4c2825bf5ea1812354bddf5784d97bd1c3caacfdbc03 in /usr/bin/ "
            },
            {
                "created": "2017-02-01T12:38:44.153641548Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  WORKDIR /opt/app-root/src",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:46.27564274Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  ENTRYPOINT [\"container-entrypoint\"]",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:48.448663571Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  CMD [\"base-usage\"]",
                "empty_layer": true
            },
            {
                "created": "2017-02-01T12:38:50.598676504Z",
                "author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
                "created_by": "/bin/sh -c #(nop)  LABEL io.openshift.builder-base-version=bfd4736",
                "empty_layer": true
            }
        ]
    },
    "DefaultMountsFilePath": "",
    "Isolation": "IsolationDefault",
    "NamespaceOptions": [
        {
            "Name": "cgroup",
            "Host": true,
            "Path": ""
        },
        {
            "Name": "ipc",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "mount",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "network",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "pid",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "user",
            "Host": true,
            "Path": ""
        },
        {
            "Name": "uts",
            "Host": false,
            "Path": ""
        }
    ],
    "ConfigureNetwork": "NetworkDefault",
    "CNIPluginPath": "",
    "CNIConfigDir": "",
    "IDMappingOptions": {
        "HostUIDMapping": true,
        "HostGIDMapping": true,
        "UIDMap": [],
        "GIDMap": []
    },
    "DefaultCapabilities": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
    ],
    "AddCapabilities": [],
    "DropCapabilities": []
}

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
Without looking into the details, this looks very much like #684.

> buildah version 1.1 or 1.3 the result is the same.

v1.1 is known broken with #684, fixed in #860 (before v1.2).

But, it seems that #860 updated containers/image without updating the version in `vendor.conf`, and that allowed #904 to _revert_ the fix of #684.

So, 1.3 is broken again. The vendored version of c/image needs to be at least 66857a7ff6ed0dc8eb70b5532e9add4fd77981c4 (https://github.com/containers/image/pull/472 ).

(A possible way to ~quickly test this would be to use the 1.2 release. **Note:** To verify whether the bug has been fixed, it is necessary to _at least_ untag and re-pull all involved images; maybe deleting the container storage and starting from scratch would be easiest.)

**Comment by TomSweeneyRedHat** [comment]
@mtrmac I'll take a whack at adjusting it.  Can I bump it to the latest?  5df44e095ed826fbe2beeaabb329c749d7d6c3b6

**Comment by mtrmac** [comment]
> Can I bump it to the latest? 5df44e095ed826fbe2beeaabb329c749d7d6c3b6

I think so; there shouldn’t be any major API changes.

**Comment by llchan** [comment]
@TomSweeneyRedHat is this expected to be fixed? I'm running a fresh buildah build (commit 8ead4d2eca70cb6cf4686e11912148aef7235f84, master as of today), and I still see the emtpy layer error. What should I do to troubleshoot?

**Comment by mtrmac** [comment]
@llchan Are you using the same local container storage as when the bug has first manifested? If so, you need to untag all affected containers and pull them again with the fixed code for the fix to be effective. (Deleting the storage entirely and starting from scratch might be easiest.)

**Comment by llchan** [comment]
@mtrmac Yep, was just about to reply. I had only deleted one of the container storage dirs, didnt realize there's one in /var/lib and one in /var/run. Looks like it's working now. Thanks!

**Comment by rhatdan** [comment]
Can I close this issue now?

**Comment by olivierGATSNCF** [comment]
@rhatdan: Who is this question addressed to?

**Comment by rhatdan** [comment]
@olivierGATSNCF I guess you. Comments above indicate that some/all of these issues have been addressed.

**Comment by mtrmac** [comment]
@olivierGATSNCF 1.3 is known broken; can you upgrade to 1.4? (Don’t forget to untag images or reset the storage before testing this after an upgrade.)

**Comment by olivierGATSNCF** [comment]
@mtrmac  my build is OK with buildah 1.4. Thanks
